import "./globals.css"
import type { Metadata } from "next"
import { Archivo } from "next/font/google"
import { NextFont } from "next/dist/compiled/@next/font"
import { ConditionalHeader } from "@/providers/conditionalHeader"
import { ConditionalFooter } from "@/providers/conditionalFooter"
import { RefreshProvider } from "@/providers/RefreshToken.provider"
import { QueryClintProvider } from "@/providers/queryclient.provider"

const archivo: NextFont= Archivo({
  subsets: ['latin'], // Preloads the Latin subset (most common)
  preload: true,
});
export const metadata: Metadata= {
  title: "German W M",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased scroll-smooth bg-slate-100 ${archivo.className}`}>
        <QueryClintProvider>
          <RefreshProvider>
            <ConditionalHeader/>
            {children}
            <ConditionalFooter/>
          </RefreshProvider>
        </QueryClintProvider>
      </body>
    </html>
  )
}